
/**
* HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Friday, September 20, 2024 9:47:19 AM WET
*/

public interface HelloOperations 
{
  void hello ();
} // interface HelloOperations
